"""empty message

Revision ID: 2a15013972b7
Revises: 73b7a4ff4da3
Create Date: 2022-09-08 09:22:06.023539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a15013972b7'
down_revision = '73b7a4ff4da3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user_info', sa.Column('user_pa', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_user_info', 'user_pa')
    # ### end Alembic commands ###
