"""empty message

Revision ID: 73b7a4ff4da3
Revises: 
Create Date: 2022-09-06 23:39:47.197264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b7a4ff4da3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_board',
    sa.Column('brd_index', sa.Integer(), nullable=False),
    sa.Column('brd_user', sa.String(length=45), nullable=False),
    sa.Column('brd_title', sa.String(length=45), nullable=False),
    sa.Column('brd_content', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('brd_index')
    )
    op.create_table('tb_food_img',
    sa.Column('food_index', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=45), nullable=False),
    sa.Column('food_cal', sa.FLOAT(precision=10), nullable=True),
    sa.Column('food_img', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('food_index')
    )
    op.create_table('tb_user',
    sa.Column('user_email', sa.String(length=45), nullable=False),
    sa.Column('user_pw', sa.String(length=45), nullable=False),
    sa.Column('user_name', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('user_email')
    )
    op.create_table('tb_user_img',
    sa.Column('upload_index', sa.Integer(), nullable=False),
    sa.Column('upload_user', sa.String(length=45), nullable=True),
    sa.Column('upload_foodname', sa.String(length=45), nullable=False),
    sa.Column('upload_location', sa.String(length=45), nullable=False),
    sa.Column('upload_isnew', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['upload_user'], ['tb_user.user_email'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('upload_index')
    )
    op.create_table('tb_user_info',
    sa.Column('user_email', sa.String(length=45), nullable=False),
    sa.Column('user_weight', sa.FLOAT(precision=10), nullable=True),
    sa.Column('user_height', sa.SmallInteger(), nullable=True),
    sa.Column('user_birth', sa.Date(), nullable=True),
    sa.Column('user_cal', sa.FLOAT(precision=10), nullable=True),
    sa.Column('user_goal', sa.FLOAT(precision=10), nullable=True),
    sa.Column('user_sex', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['tb_user.user_email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_user_info')
    op.drop_table('tb_user_img')
    op.drop_table('tb_user')
    op.drop_table('tb_food_img')
    op.drop_table('tb_board')
    # ### end Alembic commands ###
